[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore Quizzando/Quizzando.csproj"]

[phases.build]
cmds = ["dotnet publish Quizzando/Quizzando.csproj -c Release -o out"]

[start]
cmd = "dotnet out/Quizzando.dll"